# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_markup_extended}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Mitch Marx}]
  s.date = %q{2011-07-01}
  s.description = %q{Represent ActiveRecord Markdown, Textile, Wiki text, RDoc columns as Markdown, Textile Wikitext, RDoc objects using various external libraries to convert to HTML. Includes markup extension methods.}
  s.email = %q{mitch.marx@mdpaladin.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/acts/as_markup.rb",
    "lib/acts_as_markup/exts/maruku.rb",
    "lib/acts_as_markup/exts/object.rb",
    "lib/acts_as_markup/exts/peg_markdown.rb",
    "lib/acts_as_markup/exts/rdiscount.rb",
    "lib/acts_as_markup/exts/rdoc.rb",
    "lib/acts_as_markup/exts/wikitext.rb",
    "lib/acts_as_markup/stringlike.rb",
    "lib/acts_as_markup_extended.rb",
    "lib/markup_extensions.rb",
    "lib/markup_methods/ahttp.rb",
    "lib/markup_methods/checklist.rb",
    "lib/markup_methods/logo.rb",
    "test/acts_as_markdown_test.rb",
    "test/acts_as_markup_extended.rb",
    "test/acts_as_markup_test.rb",
    "test/acts_as_rdoc_test.rb",
    "test/acts_as_textile_test.rb",
    "test/acts_as_wikitext_test.rb",
    "test/markup_methods_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{https://github.com/mitchmarx/acts_as_markup_extended/}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Represent ActiveRecord Markdown, Textile, Wiki text, RDoc columns as Markdown, Textile Wikitext, RDoc objects using various external libraries to convert to HTML. Includes markup extension methods.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<rdiscount>, ["~> 1.3"])
      s.add_runtime_dependency(%q<wikitext>, ["~> 2.0"])
      s.add_runtime_dependency(%q<RedCloth>, ["~> 4.2"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_dependency(%q<activerecord>, [">= 2.3.2"])
      s.add_dependency(%q<rdiscount>, ["~> 1.3"])
      s.add_dependency(%q<wikitext>, ["~> 2.0"])
      s.add_dependency(%q<RedCloth>, ["~> 4.2"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.2"])
    s.add_dependency(%q<activerecord>, [">= 2.3.2"])
    s.add_dependency(%q<rdiscount>, ["~> 1.3"])
    s.add_dependency(%q<wikitext>, ["~> 2.0"])
    s.add_dependency(%q<RedCloth>, ["~> 4.2"])
  end
end

